/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as SiteRouteRouteImport } from './routes/_site/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as DashboardPublishedRouteImport } from './routes/dashboard/published'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardDraftRouteImport } from './routes/dashboard/draft'
import { Route as DashboardBookmarksRouteImport } from './routes/dashboard/bookmarks'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTagsRouteImport } from './routes/admin/tags'
import { Route as AdminPostsRouteImport } from './routes/admin/posts'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as SitePostsSearchRouteImport } from './routes/_site/posts/search'
import { Route as SitePostsNewRouteImport } from './routes/_site/posts/new'
import { Route as SitePostsSlugRouteImport } from './routes/_site/posts/$slug'
import { Route as SitePostsEditIdRouteImport } from './routes/_site/posts/edit/$id'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRouteRoute = SiteRouteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const DashboardPublishedRoute = DashboardPublishedRouteImport.update({
  id: '/published',
  path: '/published',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDraftRoute = DashboardDraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBookmarksRoute = DashboardBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTagsRoute = AdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/_auth/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/_auth/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SitePostsSearchRoute = SitePostsSearchRouteImport.update({
  id: '/posts/search',
  path: '/posts/search',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SitePostsNewRoute = SitePostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SitePostsSlugRoute = SitePostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SitePostsEditIdRoute = SitePostsEditIdRouteImport.update({
  id: '/posts/edit/$id',
  path: '/posts/edit/$id',
  getParentRoute: () => SiteRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/bookmarks': typeof DashboardBookmarksRoute
  '/dashboard/draft': typeof DashboardDraftRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/published': typeof DashboardPublishedRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/posts/$slug': typeof SitePostsSlugRoute
  '/posts/new': typeof SitePostsNewRoute
  '/posts/search': typeof SitePostsSearchRoute
  '/posts/edit/$id': typeof SitePostsEditIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/bookmarks': typeof DashboardBookmarksRoute
  '/dashboard/draft': typeof DashboardDraftRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/published': typeof DashboardPublishedRoute
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/posts/$slug': typeof SitePostsSlugRoute
  '/posts/new': typeof SitePostsNewRoute
  '/posts/search': typeof SitePostsSearchRoute
  '/posts/edit/$id': typeof SitePostsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/bookmarks': typeof DashboardBookmarksRoute
  '/dashboard/draft': typeof DashboardDraftRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/published': typeof DashboardPublishedRoute
  '/_site/': typeof SiteIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_site/posts/$slug': typeof SitePostsSlugRoute
  '/_site/posts/new': typeof SitePostsNewRoute
  '/_site/posts/search': typeof SitePostsSearchRoute
  '/_site/posts/edit/$id': typeof SitePostsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/posts'
    | '/admin/tags'
    | '/admin/users'
    | '/dashboard/bookmarks'
    | '/dashboard/draft'
    | '/dashboard/profile'
    | '/dashboard/published'
    | '/admin/'
    | '/dashboard/'
    | '/posts/$slug'
    | '/posts/new'
    | '/posts/search'
    | '/posts/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/posts'
    | '/admin/tags'
    | '/admin/users'
    | '/dashboard/bookmarks'
    | '/dashboard/draft'
    | '/dashboard/profile'
    | '/dashboard/published'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/posts/$slug'
    | '/posts/new'
    | '/posts/search'
    | '/posts/edit/$id'
  id:
    | '__root__'
    | '/_site'
    | '/admin'
    | '/dashboard'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_auth/verify-email'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/posts'
    | '/admin/tags'
    | '/admin/users'
    | '/dashboard/bookmarks'
    | '/dashboard/draft'
    | '/dashboard/profile'
    | '/dashboard/published'
    | '/_site/'
    | '/admin/'
    | '/dashboard/'
    | '/_site/posts/$slug'
    | '/_site/posts/new'
    | '/_site/posts/search'
    | '/_site/posts/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRouteRoute: typeof SiteRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/dashboard/published': {
      id: '/dashboard/published'
      path: '/published'
      fullPath: '/dashboard/published'
      preLoaderRoute: typeof DashboardPublishedRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/draft': {
      id: '/dashboard/draft'
      path: '/draft'
      fullPath: '/dashboard/draft'
      preLoaderRoute: typeof DashboardDraftRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/bookmarks': {
      id: '/dashboard/bookmarks'
      path: '/bookmarks'
      fullPath: '/dashboard/bookmarks'
      preLoaderRoute: typeof DashboardBookmarksRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tags': {
      id: '/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AdminTagsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/posts/search': {
      id: '/_site/posts/search'
      path: '/posts/search'
      fullPath: '/posts/search'
      preLoaderRoute: typeof SitePostsSearchRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/posts/new': {
      id: '/_site/posts/new'
      path: '/posts/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof SitePostsNewRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/posts/$slug': {
      id: '/_site/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof SitePostsSlugRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/posts/edit/$id': {
      id: '/_site/posts/edit/$id'
      path: '/posts/edit/$id'
      fullPath: '/posts/edit/$id'
      preLoaderRoute: typeof SitePostsEditIdRouteImport
      parentRoute: typeof SiteRouteRoute
    }
  }
}

interface SiteRouteRouteChildren {
  SiteIndexRoute: typeof SiteIndexRoute
  SitePostsSlugRoute: typeof SitePostsSlugRoute
  SitePostsNewRoute: typeof SitePostsNewRoute
  SitePostsSearchRoute: typeof SitePostsSearchRoute
  SitePostsEditIdRoute: typeof SitePostsEditIdRoute
}

const SiteRouteRouteChildren: SiteRouteRouteChildren = {
  SiteIndexRoute: SiteIndexRoute,
  SitePostsSlugRoute: SitePostsSlugRoute,
  SitePostsNewRoute: SitePostsNewRoute,
  SitePostsSearchRoute: SitePostsSearchRoute,
  SitePostsEditIdRoute: SitePostsEditIdRoute,
}

const SiteRouteRouteWithChildren = SiteRouteRoute._addFileChildren(
  SiteRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminTagsRoute: typeof AdminTagsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminTagsRoute: AdminTagsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardBookmarksRoute: typeof DashboardBookmarksRoute
  DashboardDraftRoute: typeof DashboardDraftRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardPublishedRoute: typeof DashboardPublishedRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardBookmarksRoute: DashboardBookmarksRoute,
  DashboardDraftRoute: DashboardDraftRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardPublishedRoute: DashboardPublishedRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SiteRouteRoute: SiteRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
